# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from REST.models.base_model_ import Model
from REST import util


class Coordinate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, latitude: float=None, longitude: float=None, altitude: float=None):  # noqa: E501
        """Coordinate - a model defined in Swagger

        :param latitude: The latitude of this Coordinate.  # noqa: E501
        :type latitude: float
        :param longitude: The longitude of this Coordinate.  # noqa: E501
        :type longitude: float
        :param altitude: The altitude of this Coordinate.  # noqa: E501
        :type altitude: float
        """
        self.swagger_types = {
            'latitude': float,
            'longitude': float,
            'altitude': float
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude',
            'altitude': 'altitude'
        }
        self._latitude = latitude
        self._longitude = longitude
        self._altitude = altitude

    @classmethod
    def from_dict(cls, dikt) -> 'Coordinate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Coordinate of this Coordinate.  # noqa: E501
        :rtype: Coordinate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self) -> float:
        """Gets the latitude of this Coordinate.


        :return: The latitude of this Coordinate.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: float):
        """Sets the latitude of this Coordinate.


        :param latitude: The latitude of this Coordinate.
        :type latitude: float
        """
        if latitude is None:
            raise ValueError("Invalid value for `latitude`, must not be `None`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self) -> float:
        """Gets the longitude of this Coordinate.


        :return: The longitude of this Coordinate.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: float):
        """Sets the longitude of this Coordinate.


        :param longitude: The longitude of this Coordinate.
        :type longitude: float
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude

    @property
    def altitude(self) -> float:
        """Gets the altitude of this Coordinate.


        :return: The altitude of this Coordinate.
        :rtype: float
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude: float):
        """Sets the altitude of this Coordinate.


        :param altitude: The altitude of this Coordinate.
        :type altitude: float
        """
        if altitude is None:
            raise ValueError("Invalid value for `altitude`, must not be `None`")  # noqa: E501

        self._altitude = altitude
