# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from REST.models.base_model_ import Model
from REST import util


class MissionIdResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, mission_id: int=None):  # noqa: E501
        """MissionIdResponse - a model defined in Swagger

        :param mission_id: The mission_id of this MissionIdResponse.  # noqa: E501
        :type mission_id: int
        """
        self.swagger_types = {
            'mission_id': int
        }

        self.attribute_map = {
            'mission_id': 'missionId'
        }
        self._mission_id = mission_id

    @classmethod
    def from_dict(cls, dikt) -> 'MissionIdResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MissionIdResponse of this MissionIdResponse.  # noqa: E501
        :rtype: MissionIdResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mission_id(self) -> int:
        """Gets the mission_id of this MissionIdResponse.


        :return: The mission_id of this MissionIdResponse.
        :rtype: int
        """
        return self._mission_id

    @mission_id.setter
    def mission_id(self, mission_id: int):
        """Sets the mission_id of this MissionIdResponse.


        :param mission_id: The mission_id of this MissionIdResponse.
        :type mission_id: int
        """
        if mission_id is None:
            raise ValueError("Invalid value for `mission_id`, must not be `None`")  # noqa: E501

        self._mission_id = mission_id
