# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from REST.models.base_model_ import Model
from REST.models.command import Command  # noqa: F401,E501
from REST.models.navigation_area import NavigationArea  # noqa: F401,E501
from REST.models.task import Task  # noqa: F401,E501
from REST.models.vehicle import Vehicle  # noqa: F401,E501
from REST import util


class Mission(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, mission_id: int=None, tasks: List[Task]=None, vehicles: List[Vehicle]=None, commands: List[Command]=None, navigation_area: NavigationArea=None):  # noqa: E501
        """Mission - a model defined in Swagger

        :param mission_id: The mission_id of this Mission.  # noqa: E501
        :type mission_id: int
        :param tasks: The tasks of this Mission.  # noqa: E501
        :type tasks: List[Task]
        :param vehicles: The vehicles of this Mission.  # noqa: E501
        :type vehicles: List[Vehicle]
        :param commands: The commands of this Mission.  # noqa: E501
        :type commands: List[Command]
        :param navigation_area: The navigation_area of this Mission.  # noqa: E501
        :type navigation_area: NavigationArea
        """
        self.swagger_types = {
            'mission_id': int,
            'tasks': List[Task],
            'vehicles': List[Vehicle],
            'commands': List[Command],
            'navigation_area': NavigationArea
        }

        self.attribute_map = {
            'mission_id': 'missionId',
            'tasks': 'tasks',
            'vehicles': 'vehicles',
            'commands': 'commands',
            'navigation_area': 'navigationArea'
        }
        self._mission_id = mission_id
        self._tasks = tasks
        self._vehicles = vehicles
        self._commands = commands
        self._navigation_area = navigation_area

    @classmethod
    def from_dict(cls, dikt) -> 'Mission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Mission of this Mission.  # noqa: E501
        :rtype: Mission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mission_id(self) -> int:
        """Gets the mission_id of this Mission.


        :return: The mission_id of this Mission.
        :rtype: int
        """
        return self._mission_id

    @mission_id.setter
    def mission_id(self, mission_id: int):
        """Sets the mission_id of this Mission.


        :param mission_id: The mission_id of this Mission.
        :type mission_id: int
        """
        if mission_id is None:
            raise ValueError("Invalid value for `mission_id`, must not be `None`")  # noqa: E501

        self._mission_id = mission_id

    @property
    def tasks(self) -> List[Task]:
        """Gets the tasks of this Mission.


        :return: The tasks of this Mission.
        :rtype: List[Task]
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks: List[Task]):
        """Sets the tasks of this Mission.


        :param tasks: The tasks of this Mission.
        :type tasks: List[Task]
        """
        if tasks is None:
            raise ValueError("Invalid value for `tasks`, must not be `None`")  # noqa: E501

        self._tasks = tasks

    @property
    def vehicles(self) -> List[Vehicle]:
        """Gets the vehicles of this Mission.


        :return: The vehicles of this Mission.
        :rtype: List[Vehicle]
        """
        return self._vehicles

    @vehicles.setter
    def vehicles(self, vehicles: List[Vehicle]):
        """Sets the vehicles of this Mission.


        :param vehicles: The vehicles of this Mission.
        :type vehicles: List[Vehicle]
        """
        if vehicles is None:
            raise ValueError("Invalid value for `vehicles`, must not be `None`")  # noqa: E501

        self._vehicles = vehicles

    @property
    def commands(self) -> List[Command]:
        """Gets the commands of this Mission.


        :return: The commands of this Mission.
        :rtype: List[Command]
        """
        return self._commands

    @commands.setter
    def commands(self, commands: List[Command]):
        """Sets the commands of this Mission.


        :param commands: The commands of this Mission.
        :type commands: List[Command]
        """
        if commands is None:
            raise ValueError("Invalid value for `commands`, must not be `None`")  # noqa: E501

        self._commands = commands

    @property
    def navigation_area(self) -> NavigationArea:
        """Gets the navigation_area of this Mission.


        :return: The navigation_area of this Mission.
        :rtype: NavigationArea
        """
        return self._navigation_area

    @navigation_area.setter
    def navigation_area(self, navigation_area: NavigationArea):
        """Sets the navigation_area of this Mission.


        :param navigation_area: The navigation_area of this Mission.
        :type navigation_area: NavigationArea
        """
        if navigation_area is None:
            raise ValueError("Invalid value for `navigation_area`, must not be `None`")  # noqa: E501

        self._navigation_area = navigation_area
