# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from REST.models.base_model_ import Model
from REST.models.coordinate import Coordinate  # noqa: F401,E501
from REST import util


class NavigationArea(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, area: List[Coordinate]=None):  # noqa: E501
        """NavigationArea - a model defined in Swagger

        :param area: The area of this NavigationArea.  # noqa: E501
        :type area: List[Coordinate]
        """
        self.swagger_types = {
            'area': List[Coordinate]
        }

        self.attribute_map = {
            'area': 'area'
        }
        self._area = area

    @classmethod
    def from_dict(cls, dikt) -> 'NavigationArea':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NavigationArea of this NavigationArea.  # noqa: E501
        :rtype: NavigationArea
        """
        return util.deserialize_model(dikt, cls)

    @property
    def area(self) -> List[Coordinate]:
        """Gets the area of this NavigationArea.


        :return: The area of this NavigationArea.
        :rtype: List[Coordinate]
        """
        return self._area

    @area.setter
    def area(self, area: List[Coordinate]):
        """Sets the area of this NavigationArea.


        :param area: The area of this NavigationArea.
        :type area: List[Coordinate]
        """

        self._area = area
