# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from REST.models.base_model_ import Model
from REST.models.task_dependency import TaskDependency  # noqa: F401,E501
from REST import util


class Task(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, task_type: str=None, id: int=None, mission_id: int=None, task_status: str=None, assigned_vehicle_id: int=None, task_dependency: TaskDependency=None):  # noqa: E501
        """Task - a model defined in Swagger

        :param task_type: The task_type of this Task.  # noqa: E501
        :type task_type: str
        :param id: The id of this Task.  # noqa: E501
        :type id: int
        :param mission_id: The mission_id of this Task.  # noqa: E501
        :type mission_id: int
        :param task_status: The task_status of this Task.  # noqa: E501
        :type task_status: str
        :param assigned_vehicle_id: The assigned_vehicle_id of this Task.  # noqa: E501
        :type assigned_vehicle_id: int
        :param task_dependency: The task_dependency of this Task.  # noqa: E501
        :type task_dependency: TaskDependency
        """
        self.swagger_types = {
            'task_type': str,
            'id': int,
            'mission_id': int,
            'task_status': str,
            'assigned_vehicle_id': int,
            'task_dependency': TaskDependency
        }

        self.attribute_map = {
            'task_type': 'taskType',
            'id': 'id',
            'mission_id': 'missionId',
            'task_status': 'taskStatus',
            'assigned_vehicle_id': 'assignedVehicleId',
            'task_dependency': 'taskDependency'
        }
        self._task_type = task_type
        self._id = id
        self._mission_id = mission_id
        self._task_status = task_status
        self._assigned_vehicle_id = assigned_vehicle_id
        self._task_dependency = task_dependency

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def task_type(self) -> str:
        """Gets the task_type of this Task.


        :return: The task_type of this Task.
        :rtype: str
        """
        return self._task_type

    @task_type.setter
    def task_type(self, task_type: str):
        """Sets the task_type of this Task.


        :param task_type: The task_type of this Task.
        :type task_type: str
        """
        allowed_values = ["TRANSIT", "SURVEY", "TREATMENT"]  # noqa: E501
        if task_type not in allowed_values:
            raise ValueError(
                "Invalid value for `task_type` ({0}), must be one of {1}"
                .format(task_type, allowed_values)
            )

        self._task_type = task_type

    @property
    def id(self) -> int:
        """Gets the id of this Task.


        :return: The id of this Task.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Task.


        :param id: The id of this Task.
        :type id: int
        """

        self._id = id

    @property
    def mission_id(self) -> int:
        """Gets the mission_id of this Task.


        :return: The mission_id of this Task.
        :rtype: int
        """
        return self._mission_id

    @mission_id.setter
    def mission_id(self, mission_id: int):
        """Sets the mission_id of this Task.


        :param mission_id: The mission_id of this Task.
        :type mission_id: int
        """

        self._mission_id = mission_id

    @property
    def task_status(self) -> str:
        """Gets the task_status of this Task.


        :return: The task_status of this Task.
        :rtype: str
        """
        return self._task_status

    @task_status.setter
    def task_status(self, task_status: str):
        """Sets the task_status of this Task.


        :param task_status: The task_status of this Task.
        :type task_status: str
        """
        allowed_values = ["NotAssigned"]  # noqa: E501
        if task_status not in allowed_values:
            raise ValueError(
                "Invalid value for `task_status` ({0}), must be one of {1}"
                .format(task_status, allowed_values)
            )

        self._task_status = task_status

    @property
    def assigned_vehicle_id(self) -> int:
        """Gets the assigned_vehicle_id of this Task.


        :return: The assigned_vehicle_id of this Task.
        :rtype: int
        """
        return self._assigned_vehicle_id

    @assigned_vehicle_id.setter
    def assigned_vehicle_id(self, assigned_vehicle_id: int):
        """Sets the assigned_vehicle_id of this Task.


        :param assigned_vehicle_id: The assigned_vehicle_id of this Task.
        :type assigned_vehicle_id: int
        """

        self._assigned_vehicle_id = assigned_vehicle_id

    @property
    def task_dependency(self) -> TaskDependency:
        """Gets the task_dependency of this Task.


        :return: The task_dependency of this Task.
        :rtype: TaskDependency
        """
        return self._task_dependency

    @task_dependency.setter
    def task_dependency(self, task_dependency: TaskDependency):
        """Sets the task_dependency of this Task.


        :param task_dependency: The task_dependency of this Task.
        :type task_dependency: TaskDependency
        """

        self._task_dependency = task_dependency
