# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feedback.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'feedback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65\x65\x64\x62\x61\x63k.proto\x12\x16\x66\x65\x65\x64\x62\x61\x63k_communication\"#\n\x0f\x46\x65\x65\x64\x62\x61\x63kRequest\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x01 \x03(\t\"(\n\x10\x46\x65\x65\x64\x62\x61\x63kResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2|\n\x15\x46\x65\x65\x64\x62\x61\x63kCommunication\x12\x63\n\x0cSendFeedback\x12\'.feedback_communication.FeedbackRequest\x1a(.feedback_communication.FeedbackResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feedback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDBACKREQUEST']._serialized_start=42
  _globals['_FEEDBACKREQUEST']._serialized_end=77
  _globals['_FEEDBACKRESPONSE']._serialized_start=79
  _globals['_FEEDBACKRESPONSE']._serialized_end=119
  _globals['_FEEDBACKCOMMUNICATION']._serialized_start=121
  _globals['_FEEDBACKCOMMUNICATION']._serialized_end=245
# @@protoc_insertion_point(module_scope)
