# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x15metrics_communication\"!\n\x0eMetricsRequest\x12\x0f\n\x07metrics\x18\x01 \x03(\t\"\'\n\x0fMetricsResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2v\n\x14MetricsCommunication\x12^\n\x0bSendMetrics\x12%.metrics_communication.MetricsRequest\x1a&.metrics_communication.MetricsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSREQUEST']._serialized_start=40
  _globals['_METRICSREQUEST']._serialized_end=73
  _globals['_METRICSRESPONSE']._serialized_start=75
  _globals['_METRICSRESPONSE']._serialized_end=114
  _globals['_METRICSCOMMUNICATION']._serialized_start=116
  _globals['_METRICSCOMMUNICATION']._serialized_end=234
# @@protoc_insertion_point(module_scope)
