# Train images
train: data_directory\train.txt

# Validation images
val: data_directory\val.txt

# Test images
test: data_directory\test.txt

# Number of classes
nc: 3

# Class names
names: ['Chardonnay', 'PinotNoir', 'PinotGris']
