services:
  ros2_drone_1:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2_drone_1:latest
    networks:
      fleet_net:
        ipv4_address: 192.168.100.129
    ports:
      - "51002:51002"
      - "51003:51003"
      - "51004:51004"
    container_name: ros2_drone_1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./Logs:/home/ros2_ws/Logs

networks:
  fleet_net:
    external: true
