"""
gRPC ROS2 Prescription Map Communication Module
===============================================

This module provides prescription map (PM) data transmission from the drone to 
Mission Management via gRPC communication. It handles the upload of agricultural
prescription maps generated during drone missions for centralized storage,
analysis, and distribution to ground systems.

The module implements a client-only architecture where the drone acts as a gRPC
client to transmit prescription map data to the Mission Management system for
agricultural workflow coordination and field management operations.

.. module:: grpc_drone_pm
    :synopsis: Provides unidirectional gRPC communication for prescription map data transmission

Workflow
--------
Prescription Map Transmission Pipeline:
    1. **PM Data Preparation**: Collect generated prescription map data from analysis
    2. **Data Transmission**: Send PM data to Mission Management via gRPC client
    3. **Acknowledgment Processing**: Receive and log transmission confirmation
    4. **Error Recovery**: Handle connection failures with retry mechanisms

Communication Architecture:
    - **Outbound Channel**: Drone → Mission Management (Port 51003)
    - **Protocol**: gRPC with protobuf PMRequest messages
    - **Trigger**: On-demand transmission when prescription maps are generated
    - **Data Type**: Agricultural prescription map data with treatment recommendations

Agricultural Context
--------------------
Prescription Maps contain:
    - **Treatment Areas**: Geographic zones requiring specific treatments
    - **Application Rates**: Precise dosage amounts per treatment zone
    - **Treatment Types**: Pesticide, fertilizer, or other agricultural inputs
    - **Spatial Coordinates**: GPS coordinates for precise application zones
    - **Analysis Results**: AI-derived recommendations from image analysis

Features
--------
- **On-Demand Transmission**: PM data sent when generated during missions
- **Agricultural Data Format**: Specialized prescription map data structures
- **Mission Management Integration**: Direct upload to central agricultural system
- **Robust Error Handling**: Automatic retry on connection failures
- **Precision Agriculture**: Support for variable-rate application workflows
- **Field Coordination**: Enable ground crew coordination with aerial data

Functions
---------
.. autofunction:: run_pm_client

Protocol Buffer Definitions
---------------------------
- **pm_pb2**: Prescription map message structures for Mission Management communication

Port Configuration
------------------
- **Port 51003**: Outbound prescription map transmission to Mission Management

Prescription Map Data Structure
------------------------------
PM data typically includes:
    - **Field Identification**: Field ID, mission ID, and timestamp
    - **Treatment Zones**: Geographic polygons with treatment specifications
    - **Application Parameters**: Rate, timing, and method recommendations
    - **Quality Metrics**: Confidence scores and validation data
    - **Metadata**: Analysis parameters, environmental conditions, equipment used

Notes
-----
This module requires an active Mission Management system listening on port 51003
for successful prescription map transmission. PM data is typically generated by
image analysis workflows and transmitted for field management coordination.

See Also
--------
PrescriptionMap.pm_manager : Prescription map generation and management
Images.analyze_image : Image analysis producing prescription map data
GRPC.definitions.pm_pb2 : Protocol buffer message definitions for PM data
"""

import grpc
import time
import queue
import logging
from typing import Dict, Any, Union

from GRPC.definitions.pm_pb2 import PMRequest
from GRPC.definitions.pm_pb2_grpc import PMCommunicationStub

def run_pm_client(pm: Union[Dict[str, Any], str], logger: logging.Logger) -> None:
    """
    Transmit prescription map data to Mission Management system via gRPC.

    This function handles the upload of agricultural prescription map data generated
    during drone missions to the Mission Management system. It provides a critical
    link between aerial data collection and ground-based agricultural operations,
    enabling precision agriculture workflows and field management coordination.

    Parameters
    ----------
    pm : Union[Dict[str, Any], str]
        Prescription map data to be transmitted. Can be either:
        - Dict: Structured prescription map data with treatment zones and parameters
        - str: JSON-serialized prescription map data ready for transmission
        
    logger : logging.Logger
        Logger instance for recording prescription map transmission events and errors.

    Returns
    -------
    None
        Function completes after transmission attempt (successful or failed).

    Workflow
    --------
    1. **gRPC Channel Setup**: Establish insecure channel to Mission Management (localhost:51003)
    2. **Stub Creation**: Initialize PMCommunicationStub for prescription map RPC calls
    3. **Transmission Process**:
        a. **Transmission Logging**: Log PM data transmission attempt
        b. **gRPC Call**: Send PM data via SendPM RPC method
        c. **Acknowledgment**: Log successful transmission confirmation from Mission Management
    4. **Error Handling**: Handle connection and communication errors with retry delays

    Agricultural Context
    --------------------
    Prescription maps are essential for precision agriculture workflows:
        - **Variable Rate Application**: Different treatment rates for field zones
        - **Targeted Treatment**: Specific interventions based on crop health analysis
        - **Resource Optimization**: Minimize input costs while maximizing effectiveness
        - **Environmental Protection**: Reduce over-application and environmental impact
        - **Compliance Reporting**: Document treatment applications for regulations

    Configuration
    -------------
    - **Target Host**: localhost:51003 (Mission Management PM endpoint)
    - **Protocol**: gRPC with protobuf PMRequest messages
    - **Channel Type**: Insecure (for local/trusted network communication)
    - **Transmission Mode**: On-demand (triggered by prescription map generation)

    Error Handling
    --------------
    - **queue.Empty**: Legacy exception handling with brief sleep delay
    - **grpc.RpcError**: Connection failures logged with 1-second retry delay
    - **Transmission Failures**: Logged but don't prevent continued operation

    Integration Points
    ------------------
    This function is typically called from:
        - **PrescriptionMap.pm_manager**: After prescription map generation
        - **Commands.Analyze_Image**: Following image analysis completion
        - **Mission completion**: During final data transmission phases

    Data Flow
    ---------
    1. **Image Analysis** → Prescription Map Generation
    2. **PM Generation** → run_pm_client() transmission
    3. **Mission Management** → Field crew coordination
    4. **Ground Systems** → Variable rate application

    Notes
    -----
    - Function handles both structured data and pre-serialized JSON strings
    - Mission Management system must be running on port 51003 for successful operation
    - Failed transmissions are logged but don't raise exceptions
    - PM data is critical for precision agriculture workflows and field operations
    - Successful transmission enables real-time field management coordination

    See Also
    --------
    PrescriptionMap.pm_manager.send_all : Batch transmission of multiple PM datasets
    Images.analyze_image : Image analysis generating prescription map data
    Commands.Analyze_Image : Command workflow triggering PM generation
    """
    # Establish insecure gRPC channel to Mission Management PM endpoint
    channel = grpc.insecure_channel('localhost:51003')
    
    # Create stub for prescription map communication RPC calls
    stub = PMCommunicationStub(channel)

    try:
        logger.info(f"[gRPC PM] - Sending PM to ROS2")
        
        # Transmit prescription map data to Mission Management via gRPC call
        response = stub.SendPM(PMRequest(pm=pm))
        
        logger.info(f"[gRPC PM] - ACK received from ROS2")
    except queue.Empty:
        # Handle queue empty exception (legacy error handling)
        time.sleep(0.1)
    except grpc.RpcError as e:
        # Handle gRPC connection and communication errors
        logger.error(f"[gRPC PM] - Connection error: {e}")
        time.sleep(1)