# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import GRPC.mission_pb2 as mission__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MissionCommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMission = channel.unary_unary(
                '/mission_communication.MissionCommunication/SendMission',
                request_serializer=mission__pb2.MissionRequest.SerializeToString,
                response_deserializer=mission__pb2.MissionResponse.FromString,
                _registered_method=True)


class MissionCommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MissionCommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMission': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMission,
                    request_deserializer=mission__pb2.MissionRequest.FromString,
                    response_serializer=mission__pb2.MissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mission_communication.MissionCommunication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mission_communication.MissionCommunication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MissionCommunication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mission_communication.MissionCommunication/SendMission',
            mission__pb2.MissionRequest.SerializeToString,
            mission__pb2.MissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
