# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mission.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'mission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmission.proto\x12\x15mission_communication\"&\n\x0eMissionRequest\x12\x14\n\x0cmission_json\x18\x01 \x03(\t\"\'\n\x0fMissionResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2v\n\x14MissionCommunication\x12^\n\x0bSendMission\x12%.mission_communication.MissionRequest\x1a&.mission_communication.MissionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MISSIONREQUEST']._serialized_start=40
  _globals['_MISSIONREQUEST']._serialized_end=78
  _globals['_MISSIONRESPONSE']._serialized_start=80
  _globals['_MISSIONRESPONSE']._serialized_end=119
  _globals['_MISSIONCOMMUNICATION']._serialized_start=121
  _globals['_MISSIONCOMMUNICATION']._serialized_end=239
# @@protoc_insertion_point(module_scope)
