# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mqtt.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'mqtt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmqtt.proto\x12\x12mqtt_communication\"#\n\x0bMQTTRequest\x12\x14\n\x0cmqtt_message\x18\x01 \x03(\t\"$\n\x0cMQTTResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2d\n\x11MQTTCommunication\x12O\n\x08SendMQTT\x12\x1f.mqtt_communication.MQTTRequest\x1a .mqtt_communication.MQTTResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mqtt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MQTTREQUEST']._serialized_start=34
  _globals['_MQTTREQUEST']._serialized_end=69
  _globals['_MQTTRESPONSE']._serialized_start=71
  _globals['_MQTTRESPONSE']._serialized_end=107
  _globals['_MQTTCOMMUNICATION']._serialized_start=109
  _globals['_MQTTCOMMUNICATION']._serialized_end=209
# @@protoc_insertion_point(module_scope)
