# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pm.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'pm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08pm.proto\x12\x10pm_communication\"\x1f\n\tPMRequest\x12\x12\n\npm_message\x18\x01 \x03(\t\"\"\n\nPMResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2X\n\x0fPMCommunication\x12\x45\n\x06SendPM\x12\x1b.pm_communication.PMRequest\x1a\x1c.pm_communication.PMResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PMREQUEST']._serialized_start=30
  _globals['_PMREQUEST']._serialized_end=61
  _globals['_PMRESPONSE']._serialized_start=63
  _globals['_PMRESPONSE']._serialized_end=97
  _globals['_PMCOMMUNICATION']._serialized_start=99
  _globals['_PMCOMMUNICATION']._serialized_end=187
# @@protoc_insertion_point(module_scope)
