# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rest.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrest.proto\x12\x12rest_communication\"%\n\x0bRestRequest\x12\x16\n\x0emission_status\x18\x01 \x01(\t\"$\n\x0cRestResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2d\n\x11RestCommunication\x12O\n\x08SendRest\x12\x1f.rest_communication.RestRequest\x1a .rest_communication.RestResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESTREQUEST']._serialized_start=34
  _globals['_RESTREQUEST']._serialized_end=71
  _globals['_RESTRESPONSE']._serialized_start=73
  _globals['_RESTRESPONSE']._serialized_end=109
  _globals['_RESTCOMMUNICATION']._serialized_start=111
  _globals['_RESTCOMMUNICATION']._serialized_end=211
# @@protoc_insertion_point(module_scope)
