services:
  ros2_drone_3:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2_drone_3:latest
    networks:
      fleet_net:
        ipv4_address: 192.168.100.128
    ports:
      - "53002:53002"
      - "53003:53003"
      - "53004:53004"
    container_name: ros2_drone_3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./Logs:/home/ros2_ws/Logs

networks:
  fleet_net:
    external: true
