# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: db_response.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'db_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x62_response.proto\x12\x19\x64\x62_response_communication\"$\n\rDBRespRequest\x12\x13\n\x0b\x64\x62_response\x18\x01 \x03(\t\"&\n\x0e\x44\x42RespResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2z\n\x13\x44\x42RespCommunication\x12\x63\n\nSendDBResp\x12(.db_response_communication.DBRespRequest\x1a).db_response_communication.DBRespResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DBRESPREQUEST']._serialized_start=48
  _globals['_DBRESPREQUEST']._serialized_end=84
  _globals['_DBRESPRESPONSE']._serialized_start=86
  _globals['_DBRESPRESPONSE']._serialized_end=124
  _globals['_DBRESPCOMMUNICATION']._serialized_start=126
  _globals['_DBRESPCOMMUNICATION']._serialized_end=248
# @@protoc_insertion_point(module_scope)
