# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: db_request.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'db_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x62_request.proto\x12\x18\x64\x62_request_communication\"\"\n\x0c\x44\x42ReqRequest\x12\x12\n\ndb_request\x18\x01 \x03(\t\"%\n\rDBReqResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2t\n\x12\x44\x42ReqCommunication\x12^\n\tSendDBReq\x12&.db_request_communication.DBReqRequest\x1a\'.db_request_communication.DBReqResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DBREQREQUEST']._serialized_start=46
  _globals['_DBREQREQUEST']._serialized_end=80
  _globals['_DBREQRESPONSE']._serialized_start=82
  _globals['_DBREQRESPONSE']._serialized_end=119
  _globals['_DBREQCOMMUNICATION']._serialized_start=121
  _globals['_DBREQCOMMUNICATION']._serialized_end=237
# @@protoc_insertion_point(module_scope)
