# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import GRPC.db_request_pb2 as db__request__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in db_request_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DBReqCommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDBReq = channel.unary_unary(
                '/db_request_communication.DBReqCommunication/SendDBReq',
                request_serializer=db__request__pb2.DBReqRequest.SerializeToString,
                response_deserializer=db__request__pb2.DBReqResponse.FromString,
                _registered_method=True)


class DBReqCommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDBReq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBReqCommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDBReq': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDBReq,
                    request_deserializer=db__request__pb2.DBReqRequest.FromString,
                    response_serializer=db__request__pb2.DBReqResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'db_request_communication.DBReqCommunication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('db_request_communication.DBReqCommunication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DBReqCommunication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDBReq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_request_communication.DBReqCommunication/SendDBReq',
            db__request__pb2.DBReqRequest.SerializeToString,
            db__request__pb2.DBReqResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
