# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import GRPC.db_response_pb2 as db__response__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in db_response_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DBRespCommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDBResp = channel.unary_unary(
                '/db_response_communication.DBRespCommunication/SendDBResp',
                request_serializer=db__response__pb2.DBRespRequest.SerializeToString,
                response_deserializer=db__response__pb2.DBRespResponse.FromString,
                _registered_method=True)


class DBRespCommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDBResp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBRespCommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDBResp': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDBResp,
                    request_deserializer=db__response__pb2.DBRespRequest.FromString,
                    response_serializer=db__response__pb2.DBRespResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'db_response_communication.DBRespCommunication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('db_response_communication.DBRespCommunication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DBRespCommunication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDBResp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_response_communication.DBRespCommunication/SendDBResp',
            db__response__pb2.DBRespRequest.SerializeToString,
            db__response__pb2.DBRespResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
