# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plan.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'plan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nplan.proto\x12\x12plan_communication\"&\n\x10\x44ronePlanRequest\x12\x12\n\ndrone_plan\x18\x01 \x03(\t\")\n\x11\x44ronePlanResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2n\n\x11PlanCommunication\x12Y\n\x08SendPlan\x12$.plan_communication.DronePlanRequest\x1a%.plan_communication.DronePlanResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRONEPLANREQUEST']._serialized_start=34
  _globals['_DRONEPLANREQUEST']._serialized_end=72
  _globals['_DRONEPLANRESPONSE']._serialized_start=74
  _globals['_DRONEPLANRESPONSE']._serialized_end=115
  _globals['_PLANCOMMUNICATION']._serialized_start=117
  _globals['_PLANCOMMUNICATION']._serialized_end=227
# @@protoc_insertion_point(module_scope)
